[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

#[tool.poetry]
#name = "{{ cookiecutter.project_name }}"
#version = "0.1.0"
#description = "{{ cookiecutter.project_short_description }}"
#authors = "{{ cookiecutter.author_name }}"
#readme = "README.md"
#
#[tool.poetry.dev-dependencies]
#coverage = "7.0.1"
#pre-commit = "3.0.0"
#pytest = "7.2.1"
#
#[tool.poetry.dependencies]
