[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ cookiecutter.project_name }}"
version = "0.0.1"
authors = [
  { name="{{ cookiecutter.author_name }}", email="{{ cookiecutter.author_email }}" },
]
description = "{{ cookiecutter.project_short_description }}"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"

#[tool.poetry]
#name = "{{ cookiecutter.project_name }}"
#version = "0.1.0"
#description = "{{ cookiecutter.project_short_description }}"
#authors = "{{ cookiecutter.author_name }}"
#readme = "README.md"
#
#[tool.poetry.dev-dependencies]
#coverage = "7.0.1"
#pre-commit = "3.0.0"
#pytest = "7.2.1"
#
#[tool.poetry.dependencies]
